name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test -- --coverage
      - run: pnpm audit
      - run: pnpm --filter ./apps/starter build
      - name: Install Playwright Browsers
        run: pnpm -C apps/starter exec playwright install --with-deps
      - name: Run E2E tests
        run: pnpm -C apps/starter exec playwright test
      - name: Run Lighthouse CI
        run: pnpm lhci
