# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  # Upload the whole repo so runtime has package.json and workspace
  DEPLOYMENT_FOLDER: .

jobs:
# Please do not rename this job
  build-project:
    name: build Empandas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # No submodules in this repo; avoid submodule errors
          submodules: 'false'
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install and build workspace
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          TSC_COMPILE_ON_ERROR: true
        run: |
          corepack enable
          pnpm -w install --frozen-lockfile
          # Skip building the UI package to avoid type noise; dist is committed
          pnpm -w --filter ./apps/starter build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 83a7c346-692d-472d-a976-54185427e32a
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Empandas/config.yaml
          action: upload
